module.exports = {
	extends: [
		'./shared.cjs',
		'plugin:react/recommended',
		'plugin:react/jsx-runtime',
		'plugin:react-hooks/recommended',
		'plugin:jsx-a11y/recommended',
	],
	plugins: ['jsx-a11y'],
	settings: {
		react: {
			version: 'detect',
		},
	},
	rules: {
		'react/jsx-indent': ['error', 'tab', { checkAttributes: true, indentLogicalExpressions: true }],
		'react/jsx-indent-props': ['error', 'tab'],
		'react/no-unknown-property': 0,
		'react/no-children-prop': 0,
		'react/prop-types': 0,
		'react/jsx-boolean-value': ['error', 'never', { always: [] }],
		'react/jsx-closing-bracket-location': ['error', 'line-aligned'],
		'react/jsx-closing-tag-location': 'error',
		'react/jsx-curly-spacing': ['error', 'never', { allowMultiline: true }],
		'react/jsx-max-props-per-line': ['error', { maximum: 1, when: 'multiline' }],
		'react/self-closing-comp': 'error',
		'react/jsx-wrap-multilines': ['error', {
			declaration: 'parens-new-line',
			assignment: 'parens-new-line',
			return: 'parens-new-line',
			arrow: 'parens-new-line',
			condition: 'parens-new-line',
			logical: 'parens-new-line',
			prop: 'parens-new-line',
		}],
		'react/jsx-first-prop-new-line': 'error',
		'react/jsx-tag-spacing': ['error', {
			closingSlash: 'never',
			beforeSelfClosing: 'always',
			afterOpening: 'never',
			beforeClosing: 'never',
		}],
		'react/void-dom-elements-no-children': 'error',
		'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never', propElementValues: 'always' }],
		'react/jsx-one-expression-per-line': ['error', { allow: 'single-child' }],
		'react/button-has-type': ['error', {
			button: true,
			submit: true,
			reset: false,
		}],
		'react/jsx-props-no-multi-spaces': 'error',
		'react/jsx-curly-newline': 'error',
		'react/jsx-no-useless-fragment': 'error',
		'react/jsx-no-constructed-context-values': 'error',
		'react/no-unstable-nested-components': 'error',
	},
};
